- name: apache-playbook
  hosts: all
  become: true
  tasks:
  - name: Install apache
    yum:
      name: httpd
      state: present
      update_cache: yes
    when: 
        - ansible_distribution == "RedHat"
  - name: Install tomcat
    apt:
      name: tomcat
      state: present
      update_cache: yes
    when:
        - ansible_distribution == "Ubuntu"
